---
- name: Ensure /usr/local/pssid/bin directory exists
  file:
    path: /usr/local/pssid/bin
    state: directory
    mode: 0755

- name: Clone the Git repository 
  git:
    repo: "{{ git_repo_url }}"
    # dest: /home/ubuntu
    # repo: git@github.com:UMNET-perfSONAR/VT-collab.git
    dest: /usr/local/pssid/bin
    # version: main
    force: yes
  environment:
    # GIT_SSH_COMMAND: 'ssh -i /home/ubuntu/.ssh/id_rsa'
    GIT_SSH_COMMAND: 'ssh -i /home/ubuntu/.ssh/id_rsa'

- name: Install additional dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - jq
    - dhcpcd5